const $ = (q) => document.querySelector(q);
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const today = () => new Date().toISOString().slice(0,10);
const num = (v) => Number(v || 0);
const money = (v) => new Intl.NumberFormat('es-CO',{style:'currency',currency:state.config.currency || 'COP',maximumFractionDigits:0}).format(num(v));
const perc = (v) => `${(num(v)*100).toFixed(1)}%`;
const pct = (v) => num(v)/100;
const addDays = (date, days) => { const d=new Date(date||today()); d.setDate(d.getDate()+num(days)); return d.toISOString().slice(0,10); };
const nav = ['Dashboard','Insumos','Proveedores','Compras','Productos','Recetas','Producción','Ventas','Clientes','Gastos','Reportes','Configuración'];
const LS = 'amitabha-luz-infinita-v1';
let active = 'Dashboard';
let user = null;
let cloud = null;
let state = JSON.parse(localStorage.getItem(LS) || 'null') || demoState();

function demoState(){return {config:{businessName:'Amitabha Luz Infinita',instagram:'amitabha.luzinfinita',currency:'COP',targetMargin:.55,paymentFeePct:.04,soyCureDays:10,paraffinCureDays:4,costingMethod:'Promedio ponderado móvil'},suppliers:[{id:'sup1',name:'Proveedor principal',phone:'',city:'Bogotá',notes:'Demo'}],supplies:[{id:'soy',name:'Cera de soya',category:'Cera',waxType:'Soya',unitBase:'g',supplierId:'sup1',averageCost:35,currentStock:5000,minimumStock:1000,technicalNotes:'Base principal. Curado 7 a 14 días.'},{id:'paraffin',name:'Parafina',category:'Cera',waxType:'Parafina',unitBase:'g',supplierId:'sup1',averageCost:15.9,currentStock:3000,minimumStock:800,technicalNotes:'Línea secundaria.'},{id:'frag',name:'Fragancia vainilla premium',category:'Fragancia',unitBase:'g',supplierId:'sup1',averageCost:284,currentStock:800,minimumStock:150,technicalNotes:'Verificar IFRA.'},{id:'wick',name:'Mecha de madera',category:'Mecha',unitBase:'und',supplierId:'sup1',averageCost:1200,currentStock:80,minimumStock:20,technicalNotes:'Probar por diámetro.'},{id:'jar',name:'Envase vidrio 200 g',category:'Envase',unitBase:'und',supplierId:'sup1',averageCost:2100,currentStock:60,minimumStock:12,technicalNotes:'Premium.'},{id:'label',name:'Etiqueta marca + seguridad',category:'Etiqueta',unitBase:'und',supplierId:'sup1',averageCost:110,currentStock:120,minimumStock:30,technicalNotes:'Incluir advertencia.'},{id:'box',name:'Caja empaque',category:'Empaque',unitBase:'und',supplierId:'sup1',averageCost:1200,currentStock:45,minimumStock:10,technicalNotes:'Regalo.'}],products:[{id:'prod1',sku:'ALI-SOY-200',name:'Vela de soya 200 g',category:'Recipiente',waxType:'Soya',targetWeightG:200,salePrice:69900,finishedStock:12,status:'Activo'}],recipes:[{id:'rec1',productId:'prod1',name:'Receta soya premium 200 g',version:1,waxType:'Soya',targetWeightG:200,fragrancePct:8,waxSupplyId:'soy',fragranceSupplyId:'frag',wickSupplyId:'wick',vesselSupplyId:'jar',labelSupplyId:'label',packageSupplyId:'box',laborCostUnit:1875,overheadCostUnit:500,wastePct:2,cureDays:10,status:'Aprobada',notes:'Soya-first.'}],purchases:[],productions:[],sales:[],customers:[],expenses:[],movements:[]}}

async function initFirebase(){
  const cfg = window.AMITABHA_FIREBASE_CONFIG;
  if(!cfg || !cfg.apiKey) return;
  const appMod = await import('https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js');
  const authMod = await import('https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js');
  const fsMod = await import('https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js');
  const app = appMod.initializeApp(cfg); const auth = authMod.getAuth(app); const db = fsMod.getFirestore(app);
  cloud = {authMod, fsMod, auth, db};
  $('#syncStatus').textContent = 'Firebase listo';
}
async function save(){ localStorage.setItem(LS, JSON.stringify(state)); if(cloud && user?.uid){ const {doc,setDoc,serverTimestamp}=cloud.fsMod; await setDoc(doc(cloud.db,'businesses',user.uid,'app','state'),{payload:state,updatedAt:serverTimestamp()},{merge:true}); } render(); }
async function loadCloud(){ if(!cloud||!user?.uid)return; const {doc,getDoc}=cloud.fsMod; const snap=await getDoc(doc(cloud.db,'businesses',user.uid,'app','state')); if(snap.exists()){ state=snap.data().payload; localStorage.setItem(LS,JSON.stringify(state)); }}

$('#loginForm').addEventListener('submit', async (e)=>{e.preventDefault(); const email=$('#email').value||'demo@amitabha.local'; const pass=$('#password').value||'123456'; try{ if(cloud){ const {signInWithEmailAndPassword,createUserWithEmailAndPassword}=cloud.authMod; try{ user=(await signInWithEmailAndPassword(cloud.auth,email,pass)).user; }catch{ user=(await createUserWithEmailAndPassword(cloud.auth,email,pass)).user; } await loadCloud(); $('#loginStatus').textContent='Conectado con Firebase.'; } else { user={uid:'local',email}; } $('#login').classList.add('hidden'); $('#app').classList.remove('hidden'); render(); }catch(err){$('#loginStatus').textContent=err.message;} });
$('#googleLogin')?.addEventListener('click', async ()=>{ try{ if(!cloud){ $('#loginStatus').textContent='Primero configura Firebase para usar Google.'; return; } const {GoogleAuthProvider,signInWithPopup}=cloud.authMod; const provider=new GoogleAuthProvider(); provider.setCustomParameters({prompt:'select_account'}); user=(await signInWithPopup(cloud.auth,provider)).user; await loadCloud(); $('#loginStatus').textContent='Conectado con Google.'; $('#login').classList.add('hidden'); $('#app').classList.remove('hidden'); render(); }catch(err){ $('#loginStatus').textContent=err.message; } });
$('#logout').addEventListener('click',async()=>{ if(cloud) await cloud.authMod.signOut(cloud.auth); user=null; $('#app').classList.add('hidden'); $('#login').classList.remove('hidden'); });

function supply(id){return state.supplies.find(s=>s.id===id)||{};} function product(id){return state.products.find(p=>p.id===id)||{};}
function calcRecipe(r){ const fr=pct(r.fragrancePct), target=num(r.targetWeightG); const waxG=target/(1+fr), fragG=waxG*fr; const waxCost=waxG*num(supply(r.waxSupplyId).averageCost), fragCost=fragG*num(supply(r.fragranceSupplyId).averageCost); const fixed=['wickSupplyId','vesselSupplyId','labelSupplyId','packageSupplyId'].reduce((a,k)=>a+num(supply(r[k]).averageCost),0); const materials=waxCost+fragCost+fixed, waste=materials*pct(r.wastePct); const productionCost=materials+waste+num(r.laborCostUnit)+num(r.overheadCostUnit); const fee=num(state.config.paymentFeePct), margin=num(state.config.targetMargin); return {waxG,fragG,waxCost,fragCost,materials,waste,productionCost,priceFloor:productionCost/Math.max(.01,1-fee),suggestedPrice:productionCost/Math.max(.01,1-fee-margin)}; }
function stats(){ const month=today().slice(0,7); const s=state.sales.filter(x=>String(x.date).startsWith(month)); const sales=s.reduce((a,b)=>a+num(b.netTotal),0), profit=s.reduce((a,b)=>a+num(b.profit),0); return {sales,profit,units:state.sales.reduce((a,b)=>a+num(b.quantity),0),low:state.supplies.filter(x=>num(x.currentStock)<=num(x.minimumStock)).length,curing:state.productions.filter(x=>x.status==='En curado').length,margin:sales?profit/sales:0}; }
function alerts(){ const out=[]; state.supplies.forEach(s=>{if(num(s.currentStock)<=num(s.minimumStock))out.push(['Alta','Inventario crítico',`${s.name} está por debajo del stock mínimo.`])}); state.recipes.forEach(r=>{const c=calcRecipe(r), p=product(r.productId), m=p.salePrice?(p.salePrice-c.productionCost)/p.salePrice:0; if(p.salePrice && m<num(state.config.targetMargin)-.05) out.push(['Media','Margen bajo',`${p.name} tiene margen ${perc(m)} frente al objetivo ${perc(state.config.targetMargin)}.`]); if(c.fragCost/Math.max(1,c.materials)>.35) out.push(['Media','Fragancia costosa',`La fragancia supera 35% del costo de materiales en ${r.name}.`]); if(num(r.fragrancePct)>10) out.push(['Alta','Revisar IFRA',`${r.name} supera 10% de fragancia.`]);}); state.productions.filter(p=>p.status==='En curado'&&p.readyToSellDate>today()).forEach(p=>out.push(['Baja','Curado pendiente',`El lote ${p.batchCode} estará listo el ${p.readyToSellDate}.`])); return out; }
function kpis(){const s=stats(); return `<div class="kpis">${[['Ventas mes',money(s.sales)],['Ganancia mes',money(s.profit)],['Unidades vendidas',s.units],['Stock bajo',s.low],['Lotes en curado',s.curing],['Margen prom.',perc(s.margin)]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>`}
function table(rows, cols){return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(c=>`<td>${typeof c[1]==='function'?c[1](r):r[c[1]]??''}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}">Sin registros</td></tr>`}</tbody></table></div>`}
function form(fields, action){return `<form class="form-grid" data-action="${action}">${fields.map(f=>`<label>${f.label}${f.type==='select'?`<select name="${f.name}">${f.options.map(o=>`<option value="${o.v??o}">${o.t??o}</option>`).join('')}</select>`:`<input name="${f.name}" type="${f.type||'text'}" value="${f.value??''}" placeholder="${f.placeholder??''}" />`}</label>`).join('')}<button>Guardar</button></form>`}
function addHandler(){ document.querySelectorAll('form[data-action]').forEach(f=>f.onsubmit=async(e)=>{e.preventDefault(); const data=Object.fromEntries(new FormData(f).entries()); await actions[f.dataset.action](data);}); }

const actions={
  supplier: async d=>{state.suppliers.push({id:uid(),...d}); await save();},
  customer: async d=>{state.customers.push({id:uid(),...d}); await save();},
  expense: async d=>{state.expenses.push({id:uid(),...d,amount:num(d.amount)}); await save();},
  supply: async d=>{state.supplies.push({id:uid(),...d,averageCost:num(d.averageCost),currentStock:num(d.currentStock),minimumStock:num(d.minimumStock)}); await save();},
  product: async d=>{state.products.push({id:uid(),...d,targetWeightG:num(d.targetWeightG),salePrice:num(d.salePrice),finishedStock:num(d.finishedStock),status:'Activo'}); await save();},
  purchase: async d=>{const s=supply(d.supplyId), qty=num(d.quantity), unit=num(d.unitCost), subtotal=qty*unit, total=subtotal+num(d.shipping)+num(d.taxes)-num(d.discount), landed=qty?total/qty:unit, old=num(s.currentStock), avg=num(s.averageCost); s.averageCost=old+qty?((old*avg)+(qty*landed))/(old+qty):landed; s.currentStock=old+qty; s.lot=d.lot||s.lot; state.purchases.push({id:uid(),...d,quantity:qty,unitCost:unit,total,landedUnitCost:landed}); await save();},
  recipe: async d=>{state.recipes.push({id:uid(),...d,version:num(d.version||1),targetWeightG:num(d.targetWeightG),fragrancePct:num(d.fragrancePct),laborCostUnit:num(d.laborCostUnit),overheadCostUnit:num(d.overheadCostUnit),wastePct:num(d.wastePct),cureDays:num(d.cureDays),status:'Borrador'}); await save();},
  production: async d=>{const r=state.recipes.find(x=>x.id===d.recipeId), c=calcRecipe(r), units=num(d.plannedUnits), code=`ALI-${new Date().getFullYear()}-${String(state.productions.length+1).padStart(3,'0')}`; [{id:r.waxSupplyId,q:c.waxG*units},{id:r.fragranceSupplyId,q:c.fragG*units},...['wickSupplyId','vesselSupplyId','labelSupplyId','packageSupplyId'].map(k=>({id:r[k],q:units}))].filter(x=>x.id).forEach(u=>{supply(u.id).currentStock=Math.max(0,num(supply(u.id).currentStock)-u.q)}); product(r.productId).finishedStock=num(product(r.productId).finishedStock)+units; state.productions.push({id:uid(),startDate:d.startDate,recipeId:r.id,batchCode:code,plannedUnits:units,goodUnits:units,wastedUnits:0,status:'En curado',readyToSellDate:addDays(d.startDate,r.cureDays),realCost:c.productionCost*units,notes:d.notes}); await save();},
  sale: async d=>{const p=product(d.productId), r=state.recipes.find(x=>x.productId===d.productId), c=r?calcRecipe(r):{productionCost:0}, qty=num(d.quantity), net=qty*num(d.unitPrice)-num(d.discount)-num(d.fees), cost=c.productionCost*qty, profit=net-cost; p.finishedStock=Math.max(0,num(p.finishedStock)-qty); state.sales.push({id:uid(),...d,quantity:qty,unitPrice:num(d.unitPrice),netTotal:net,costOfSale:cost,profit,margin:net?profit/net:0,status:'Pagada'}); await save();},
  config: async d=>{state.config={...state.config,...d,targetMargin:pct(d.targetMargin),paymentFeePct:pct(d.paymentFeePct),soyCureDays:num(d.soyCureDays),paraffinCureDays:num(d.paraffinCureDays)}; await save();}
};

function render(){ $('#screenTitle').textContent=active; $('#pill').textContent=`${state.config.currency} · ${state.config.costingMethod}`; $('#nav').innerHTML=nav.map(x=>`<button class="${active===x?'active':''}" data-nav="${x}">${x}</button>`).join(''); document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{active=b.dataset.nav;render()}); const c=$('#content'); const a=alerts();
 // 📷 REEMPLAZAR: cambia heroPhoto por la URL de tu foto real cuando la tengas
 const heroPhoto='https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=75&auto=format&fit=crop';
 const heroArt=`<span class="hero-art" aria-hidden="true"><svg viewBox="0 0 120 130" fill="none"><ellipse cx="60" cy="122" rx="44" ry="5" fill="#b76e79" opacity=".18"/><rect x="38" y="52" width="44" height="70" rx="10" fill="#fbe3ec"/><rect x="38" y="52" width="44" height="12" rx="6" fill="#f4b8cd"/><path d="M60 38c-8.5-9.5-6-18 0-25 6 7 8.5 15.5 0 25z" fill="#f0b46a"/><path d="M60 37c-4.2-5.4-3-10 0-14 3 4 4.2 8.6 0 14z" fill="#fdedd2"/><line x1="60" y1="44" x2="60" y2="52" stroke="#b76e79" stroke-width="3" stroke-linecap="round"/><path d="M60 86c-3-3.2-7.4-2.8-7.4 1 0 2.8 4 5.7 7.4 7.9 3.4-2.2 7.4-5.1 7.4-7.9 0-3.8-4.4-4.2-7.4-1z" fill="#e8a8bf"/><path d="M22 30l2 4.8 4.8 2-4.8 2-2 4.8-2-4.8-4.8-2 4.8-2z" fill="#cdb8e6"/><path d="M98 24l1.6 3.9 3.9 1.6-3.9 1.6-1.6 3.9-1.6-3.9-3.9-1.6 3.9-1.6z" fill="#f7cfdd"/></svg></span>`;
 if(active==='Dashboard') c.innerHTML=`<div class="grid"><div class="hero card"><img class="hero-photo" src="${heroPhoto}" alt="" loading="lazy" onerror="this.style.display='none'"/><div><span class="hero-eyebrow">Software especializado</span><h2>Controla costo, receta, lote, curado y utilidad de cada vela.</h2><p>Arquitectura soya-first con soporte para parafina. Funciona en computador y celular.</p></div>${heroArt}<button data-go="Recetas">Crear receta</button></div>${kpis()}<div class="two"><div class="card"><h2>Alertas inteligentes</h2>${alertHtml(a)}</div><div class="card"><h2>Accesos rápidos</h2><div class="quick">${['Insumos','Compras','Recetas','Producción','Ventas','Reportes'].map(x=>`<button data-go="${x}">${x}</button>`).join('')}</div></div></div></div>`;
 if(active==='Insumos') c.innerHTML=`<div class="card"><h2>Inventario de insumos</h2>${form([{name:'name',label:'Nombre'},{name:'category',label:'Categoría',type:'select',options:['Cera','Fragancia','Mecha','Envase','Tapa','Etiqueta','Empaque','Colorante','Herramienta','Otro']},{name:'waxType',label:'Tipo cera',type:'select',options:['','Soya','Parafina','Otra']},{name:'unitBase',label:'Unidad',type:'select',options:['g','ml','und','m']},{name:'supplierId',label:'Proveedor',type:'select',options:state.suppliers.map(s=>({v:s.id,t:s.name}))},{name:'averageCost',label:'Costo unitario',type:'number'},{name:'currentStock',label:'Stock actual',type:'number'},{name:'minimumStock',label:'Stock mínimo',type:'number'},{name:'technicalNotes',label:'Notas'}],'supply')}${table(state.supplies,[['Insumo','name'],['Categoría','category'],['Cera','waxType'],['Stock',r=>`${Number(r.currentStock).toFixed(1)} ${r.unitBase}`],['Costo',r=>money(r.averageCost)],['Mínimo','minimumStock'],['Notas','technicalNotes']])}</div>`;
 if(active==='Proveedores') c.innerHTML=`<div class="card"><h2>Proveedores</h2>${form([{name:'name',label:'Nombre'},{name:'phone',label:'Teléfono'},{name:'city',label:'Ciudad'},{name:'notes',label:'Notas'}],'supplier')}${table(state.suppliers,[['Nombre','name'],['Teléfono','phone'],['Ciudad','city'],['Notas','notes']])}</div>`;
 if(active==='Compras') c.innerHTML=`<div class="card"><h2>Compras y costo promedio</h2>${form([{name:'date',label:'Fecha',type:'date',value:today()},{name:'supplyId',label:'Insumo',type:'select',options:state.supplies.map(s=>({v:s.id,t:s.name}))},{name:'quantity',label:'Cantidad',type:'number'},{name:'unitCost',label:'Costo unitario',type:'number'},{name:'shipping',label:'Envío',type:'number',value:0},{name:'taxes',label:'Impuestos',type:'number',value:0},{name:'discount',label:'Descuento',type:'number',value:0},{name:'lot',label:'Lote'}],'purchase')}${table(state.purchases,[['Fecha','date'],['Insumo',r=>supply(r.supplyId).name],['Cantidad','quantity'],['Costo aterrizado',r=>money(r.landedUnitCost)],['Total',r=>money(r.total)]])}</div>`;
 if(active==='Productos') c.innerHTML=`<div class="card"><h2>Productos</h2>${form([{name:'sku',label:'SKU'},{name:'name',label:'Nombre'},{name:'category',label:'Tipo'},{name:'waxType',label:'Cera',type:'select',options:['Soya','Parafina','Otra']},{name:'targetWeightG',label:'Peso g',type:'number'},{name:'salePrice',label:'Precio',type:'number'},{name:'finishedStock',label:'Stock terminado',type:'number'}],'product')}${table(state.products,[['SKU','sku'],['Producto','name'],['Cera','waxType'],['Peso','targetWeightG'],['Precio',r=>money(r.salePrice)],['Stock','finishedStock']])}</div>`;
 if(active==='Recetas') c.innerHTML=`<div class="card"><h2>Recetas y costos</h2>${form([{name:'productId',label:'Producto',type:'select',options:state.products.map(p=>({v:p.id,t:p.name}))},{name:'name',label:'Nombre receta'},{name:'version',label:'Versión',type:'number',value:1},{name:'waxType',label:'Cera',type:'select',options:['Soya','Parafina']},{name:'targetWeightG',label:'Peso final g',type:'number',value:200},{name:'fragrancePct',label:'Fragancia %',type:'number',value:8},{name:'waxSupplyId',label:'Insumo cera',type:'select',options:state.supplies.filter(s=>s.category==='Cera').map(s=>({v:s.id,t:s.name}))},{name:'fragranceSupplyId',label:'Fragancia',type:'select',options:state.supplies.filter(s=>s.category==='Fragancia').map(s=>({v:s.id,t:s.name}))},{name:'wickSupplyId',label:'Mecha',type:'select',options:state.supplies.filter(s=>s.category==='Mecha').map(s=>({v:s.id,t:s.name}))},{name:'vesselSupplyId',label:'Envase',type:'select',options:state.supplies.filter(s=>s.category==='Envase').map(s=>({v:s.id,t:s.name}))},{name:'labelSupplyId',label:'Etiqueta',type:'select',options:state.supplies.filter(s=>s.category==='Etiqueta').map(s=>({v:s.id,t:s.name}))},{name:'packageSupplyId',label:'Empaque',type:'select',options:state.supplies.filter(s=>s.category==='Empaque').map(s=>({v:s.id,t:s.name}))},{name:'laborCostUnit',label:'Mano obra',type:'number',value:1800},{name:'overheadCostUnit',label:'Overhead',type:'number',value:500},{name:'wastePct',label:'Merma %',type:'number',value:2},{name:'cureDays',label:'Curado días',type:'number',value:10},{name:'notes',label:'Notas'}],'recipe')}<div class="cards">${state.recipes.map(r=>recipeCard(r)).join('')}</div></div>`;
 if(active==='Producción') c.innerHTML=`<div class="card"><h2>Producción por lote</h2>${form([{name:'startDate',label:'Fecha inicio',type:'date',value:today()},{name:'recipeId',label:'Receta',type:'select',options:state.recipes.map(r=>({v:r.id,t:r.name}))},{name:'plannedUnits',label:'Unidades',type:'number',value:12},{name:'notes',label:'Observaciones'}],'production')}${table(state.productions,[['Lote','batchCode'],['Inicio','startDate'],['Receta',r=>state.recipes.find(x=>x.id===r.recipeId)?.name],['Unidades','plannedUnits'],['Estado','status'],['Listo venta','readyToSellDate'],['Costo lote',r=>money(r.realCost)]])}</div>`;
 if(active==='Ventas') c.innerHTML=`<div class="card"><h2>Ventas</h2>${form([{name:'date',label:'Fecha',type:'date',value:today()},{name:'customerId',label:'Cliente',type:'select',options:[{v:'',t:'Sin cliente'},...state.customers.map(c=>({v:c.id,t:c.name}))]},{name:'channel',label:'Canal',type:'select',options:['Directo','WhatsApp','Instagram','Feria','Tienda','Marketplace','Otro']},{name:'productId',label:'Producto',type:'select',options:state.products.map(p=>({v:p.id,t:p.name}))},{name:'quantity',label:'Cantidad',type:'number',value:1},{name:'unitPrice',label:'Precio unitario',type:'number',value:69900},{name:'discount',label:'Descuento',type:'number',value:0},{name:'fees',label:'Comisiones',type:'number',value:0},{name:'paymentMethod',label:'Medio pago',type:'select',options:['Efectivo','Nequi','Daviplata','Transferencia','Tarjeta','Otro']}],'sale')}${table(state.sales,[['Fecha','date'],['Producto',r=>product(r.productId).name],['Cant.','quantity'],['Neto',r=>money(r.netTotal)],['Ganancia',r=>money(r.profit)],['Margen',r=>perc(r.margin)],['Canal','channel']])}</div>`;
 if(active==='Clientes') c.innerHTML=`<div class="card"><h2>Clientes</h2>${form([{name:'name',label:'Nombre'},{name:'customerType',label:'Tipo'},{name:'phone',label:'Teléfono'},{name:'email',label:'Email'},{name:'city',label:'Ciudad'},{name:'instagram',label:'Instagram'},{name:'notes',label:'Notas'}],'customer')}${table(state.customers,[['Nombre','name'],['Tipo','customerType'],['Teléfono','phone'],['Ciudad','city'],['Instagram','instagram']])}</div>`;
 if(active==='Gastos') c.innerHTML=`<div class="card"><h2>Gastos</h2>${form([{name:'date',label:'Fecha',type:'date',value:today()},{name:'category',label:'Categoría'},{name:'description',label:'Descripción'},{name:'amount',label:'Monto',type:'number'}],'expense')}${table(state.expenses,[['Fecha','date'],['Categoría','category'],['Descripción','description'],['Monto',r=>money(r.amount)]])}</div>`;
 if(active==='Reportes') c.innerHTML=`<div class="grid">${kpis()}<div class="two"><div class="card"><h2>Rentabilidad por producto</h2>${table(state.products.map(p=>{const ss=state.sales.filter(s=>s.productId===p.id);return{id:p.id,name:p.name,units:ss.reduce((a,b)=>a+num(b.quantity),0),revenue:ss.reduce((a,b)=>a+num(b.netTotal),0),profit:ss.reduce((a,b)=>a+num(b.profit),0)}}),[['Producto','name'],['Unidades','units'],['Ventas',r=>money(r.revenue)],['Ganancia',r=>money(r.profit)]])}</div><div class="card"><h2>Alertas</h2>${alertHtml(a)}</div></div><div class="card"><h2>Comparativo soya vs parafina</h2>${table(['Soya','Parafina'].map(t=>({id:t,type:t,products:state.products.filter(p=>p.waxType===t).length,sales:state.sales.filter(s=>product(s.productId).waxType===t).reduce((x,y)=>x+num(y.netTotal),0)})),[['Tipo','type'],['Productos','products'],['Ventas',r=>money(r.sales)]])}</div></div>`;
 if(active==='Configuración') c.innerHTML=`<div class="card"><h2>Configuración</h2>${form([{name:'businessName',label:'Negocio',value:state.config.businessName},{name:'instagram',label:'Instagram',value:state.config.instagram},{name:'currency',label:'Moneda',value:state.config.currency},{name:'targetMargin',label:'Margen objetivo %',type:'number',value:num(state.config.targetMargin)*100},{name:'paymentFeePct',label:'Fee pasarela %',type:'number',value:num(state.config.paymentFeePct)*100},{name:'soyCureDays',label:'Curado soya',type:'number',value:state.config.soyCureDays},{name:'paraffinCureDays',label:'Curado parafina',type:'number',value:state.config.paraffinCureDays}],'config')}<div class="actions"><button id="exportJson">Exportar JSON</button><button id="importJson">Importar JSON</button><button id="restoreDemo">Restaurar demo</button></div><textarea id="backup" rows="12" placeholder="Aquí aparecerá o pega tu respaldo JSON"></textarea></div>`;
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{active=b.dataset.go;render()}); addHandler(); bindConfigButtons(); }
function recipeCard(r){const c=calcRecipe(r), p=product(r.productId); return `<article class="recipe"><h3>${r.name}</h3><p>${p.name||''} · ${r.waxType}</p><div class="mini-grid"><span>Cera: <b>${c.waxG.toFixed(1)} g</b></span><span>Fragancia: <b>${c.fragG.toFixed(1)} g</b></span><span>Costo unidad: <b>${money(c.productionCost)}</b></span><span>Precio mínimo: <b>${money(c.priceFloor)}</b></span><span>Precio sugerido: <b>${money(c.suggestedPrice)}</b></span><span>Curado: <b>${r.cureDays} días</b></span></div></article>`}
function alertHtml(a){return a.length?`<div class="alerts">${a.map(x=>`<div class="alert ${x[0].toLowerCase()}"><strong>${x[1]}</strong><p>${x[2]}</p><small>${x[0]}</small></div>`).join('')}</div>`:`<p class="muted">Sin alertas por ahora.</p>`}
function bindConfigButtons(){ const ex=$('#exportJson'); if(ex) ex.onclick=()=>$('#backup').value=JSON.stringify(state,null,2); const im=$('#importJson'); if(im) im.onclick=async()=>{try{state=JSON.parse($('#backup').value); await save();}catch{alert('JSON inválido')}}; const re=$('#restoreDemo'); if(re) re.onclick=async()=>{state=demoState(); await save();}; }

initFirebase().then(()=>render()).catch(()=>render());
